# Site settings
name: Easy Engineering - Blog
title: Easy Engineering - Blog
email: blog@easy-eng.net
description: "Miscellaneous posts from easy-eng.net site."
baseurl: ""
url: "http://localhost:4000/"

# Build settings
markdown: kramdown
permalinks: pretty

highlighter: pygments
